MOCK_APPLICATION = {
    "applicationId": "SE20260001",
    "applicantId": "APL-1001",
    "programmeId": "mca",
    "applicationMode": "Regular",
    "fullName": "Hemanth M.P.",
    "dob": "2001-06-14",
    "gender": "Male",
    "nationality": "Indian",
    "email": "hemanth@example.com",
    "mobile": "9876543210",
    "address": "123 Anna Salai",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "pinCode": "600001",
    "tenthBoard": "State Board",
    "tenthPercentage": "88",
    "twelfthBoard": "State Board",
    "twelfthPercentage": "84",
    "ugDegree": "B.Sc. Computer Science",
    "university": "Crescent University",
    "graduationYear": 2023,
    "cgpa": "6.969",
    "status": "WAITING_FOR_DOCUMENTS",
    "progressPercent": 45,
    "documentsSubmitted": 4,
    "documentsRequired": 6,
    "eligibilityStatus": "PENDING",
    "unreadNotifications": 3,
    "nextAction": "2 documents are still required.",
    "currentAction": "Smart Enroll is verifying your submitted documents and waiting for the remaining required files.",
    "submittedAt": "2026-09-05T10:00:00Z",
    "createdAt": "2026-09-01T09:00:00Z",
    "updatedAt": "2026-09-05T10:00:00Z",
}
