import { useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import PageHeader from "../../components/PageHeader";
import StatusBadge from "../../components/StatusBadge";
import { getAdminApplicationDetails } from "../../services/api";
import "./Admin.css";
export default function ApplicationDetails(){const {id}=useParams();const navigate=useNavigate();const [d,setD]=useState(undefined);useEffect(()=>{getAdminApplicationDetails(id).then(setD)},[id]);if(d===undefined)return <p>Loading application details...</p>;if(!d)return <div><PageHeader title="Application not found"/><button className="btn btn-secondary" onClick={()=>navigate('/admin/applications')}>Back to Applications</button></div>;
return <div><PageHeader title={d.applicationId} subtitle={`${d.applicantName} · ${d.programme?.fullName??d.programmeId}`} actions={<button className="btn btn-secondary btn-sm" onClick={()=>navigate('/admin/applications')}>Back</button>}/>
<div className="admin-detail-grid"><section className="card admin-section"><h2>Applicant & Application</h2><dl className="admin-kv"><dt>Name</dt><dd>{d.applicantName}</dd><dt>Email</dt><dd>{d.email}</dd><dt>Programme</dt><dd>{d.programme?.name??d.programmeId}</dd><dt>Submitted</dt><dd>{d.submittedAt}</dd><dt>Application Status</dt><dd><StatusBadge code={d.status}/></dd><dt>Eligibility</dt><dd><StatusBadge code={d.eligibility?.overall??d.eligibilityStatus}/></dd></dl></section>
<section className="card admin-section"><h2>Academic Information</h2><dl className="admin-kv"><dt>Qualification</dt><dd>{d.academic?.qualification??'—'}</dd><dt>Institution</dt><dd>{d.academic?.institution??'—'}</dd><dt>Result</dt><dd>{d.academic?.result??'—'}</dd><dt>Current Smart Enroll Action</dt><dd>{d.currentAction}</dd></dl></section></div>
<section className="card admin-section"><h2>Documents & Verification</h2>{d.documents.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Document</th><th>File</th><th>Status</th><th>Authoritative Verification</th></tr></thead><tbody>{d.documents.map(doc=><tr key={doc.id}><td>{doc.name}</td><td>{doc.fileName??'Not uploaded'}</td><td><StatusBadge code={doc.status}/></td><td>{doc.details?.authoritative?.status?<StatusBadge code={doc.details.authoritative.status}/>:<span className="admin-muted">Not available / pending</span>}</td></tr>)}</tbody></table></div>:<p className="admin-muted">Detailed document records are not populated for this demonstration applicant.</p>}</section>
<div className="admin-detail-grid"><section className="card admin-section"><h2>Processing Timeline</h2><div className="admin-timeline">{d.timeline?.stages?.map(s=><div className={`admin-stage ${s.state.toLowerCase()}`} key={s.label}><span className="admin-stage-dot"/><div><span className="admin-stage-label">{s.label}</span><div className="admin-muted">{s.state}</div></div></div>)}</div><p className="admin-muted">Applicant action: {d.timeline?.applicantAction}</p></section>
<section className="card admin-section"><h2>Exceptions</h2>{d.exceptions.length?<div className="admin-exception-list">{d.exceptions.map(e=><div className="admin-exception" key={e.id}><div className="admin-exception-top"><b>{e.type.replaceAll('_',' ')}</b><StatusBadge label={e.status} tone={e.status==='RESOLVED'?'success':e.status==='OPEN'?'danger':'warning'}/></div><p style={{fontSize:'13px'}}>{e.description}</p><span className="admin-muted">{e.id} · {e.createdAt}</span></div>)}</div>:<p className="admin-muted">No exceptions are associated with this application.</p>}</section></div>
</div>}
